### ISSUE TITLE
Docs: Deployment?

### ISSUE THREAD

**Issue by spekulatius** [lightpack/lightpack#12]
Hey @lightpack,

this project looks neat. Found it via your reddit post @pradeep-tiwari  👍️ 

Btw, when I looked through the docs I kind of felt I would like some more details/ideas/examples on how to deploy and run it easiest (or as intended). Not sure if I maybe missed something while looking around, but deployment was left a bit unclear to me. 

Peter

**Comment by pradeep-tiwari** [comment]
Hello @spekulatius, glad to know that you liked this project 😅. 

Yep, I agree with you about the docs. This projects is in its alpha version for now and its definitely needs good documentation for deploying and testing locally. I've planned to produce video tutorials in a couple of days soon (may be by the next 2-3 days). Those tutorials will cover installing the framework locally and building a sample app explaining **routing**, **controllers**, **views**, **models**, **filters**, and **events**.

Once done, will update the docs with tutorials. Meanwhile stay tuned 👍. This project needs early contributors for getting to a stable release. Thanks 😀

**Comment by spekulatius** [comment]
Awesome, that sounds great! Please ping me here when you publish something @pradeep-tiwari !

**Comment by pradeep-tiwari** [comment]
@spekulatius I've updated docs with a sample tutorial to get started with **Lightpack**. Please let me know if that helps you. In the mean time I'm planning to record video tutorial for the same. Then I will move on to enhancing docs for individual components such database, ORM, filters, etc. If you have any suggestions for the framework, ping it here. 

**Tutorial Link Here** [https://lightpack.github.io/docs/#/sample-tutorial](https://lightpack.github.io/docs/#/sample-tutorial)

**Comment by spekulatius** [comment]
I assume `php -S 127.0.0.1:8080` is for local development only, is it @pradeep-tiwari? Or would you use it on prod like this too?

**Comment by lightpack** [comment]
Nope, only for local.

**Comment by lightpack** [comment]
@spekulatius Nope, only for local development.

**Comment by spekulatius** [comment]
Yeah, okay - good. That confirms my impression - what would you do for production hosting?

**Comment by lightpack** [comment]
@spekulatius It is advisable to serve project from `public` folder in production but because the project is yet in **alpha** version, I'm not concerned about production issues right now. I've planned to separate the **framework** as a separate composer package so that it becomes  easier for devs to update the project. Once that is done, I'll release the first stable version with few more unit tests to support the framework. I expect this to be done by the mid of this month end. The stable release will definitely have an updated docs with production deployment notes. 🙂

**Comment by spekulatius** [comment]
Awesome, sounds good! Keep me posted!
