### ISSUE TITLE
excuse me, how to use db query builder？

### ISSUE THREAD

**Issue by wfsdaj** [lightpack/lightpack#129]
HomeController.php
```
$users = app('db')->table('users')->get();
app('response')->render('home', [
     'users' => $users,
]);
```

views/home.php
```
var_dump($users);
```

the result is :

``500 Unknown Reason``

**Comment by pradeep-tiwari** [comment]
Hello @wfsdaj 

Sorry for the documentation. I've updated the docs for query builder. The methods are `fetchAll()` and `fetchOne()`.

```
$users = app('db')->table('users')->fetchAll();

app('response')->render('home', [
     'users' => $users,
]);
```

**Comment by pradeep-tiwari** [comment]
@wfsdaj Also I will soon freeze all the method APIs and will release the first stable version. Meanwhile I will to add more unit tests and improve documentation with possible video tutorials.

I expect this to happen by the end of this month. Please stay notified 👍

**Comment by wfsdaj** [comment]
Thanks, it has been solved.
In addition, How to trigger the routenotfoundexception error?
All my mistakes are 500.
![image](https://user-images.githubusercontent.com/36911167/132988013-b5bd8298-6504-4679-b98a-e7a0c23c45d6.png)

**Comment by pradeep-tiwari** [comment]
In development mode, `RouteNotFoundException` will be thrown for non-existing routes but in production you should see something like this and it takes care of setting appropriate response code: 
<img width="566" alt="Screenshot 2021-09-12 at 7 44 52 PM" src="https://user-images.githubusercontent.com/12413742/132991054-a3c587b4-3b1b-4e96-9eab-86ec92a39f90.png">
